### ISSUE TITLE
A problem when I run your code

### ISSUE THREAD

**Issue by xiehousen** [Duankaiwen/LSNet#2]
When I run the code, I meet one problem that I cannot solve.

The error is:
one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [2, 9, 7, 5]], which is output 0 of AsStridedBackward, is at version 6; expected version 4 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

the mmdet version is 2.2.0, and the pytorch version is 1.7.0

Thanks a lot for your help.

**Comment by Duankaiwen** [comment]
Could i check your full log?

**Comment by xiehousen** [comment]
> Could i check your full log?

Yes, of course.

[log.txt](https://github.com/Duankaiwen/LSNet/files/6402876/log.txt)

Thank you for your help.

**Comment by Duankaiwen** [comment]
@xiehousen Please try to use Pytorch 1.5.0

**Comment by xiehousen** [comment]
> @xiehousen Please try to use Pytorch 1.5.0

Pytorch 1.5.0 is OK! It's a great paper.

**Comment by eeric** [comment]
Installation instruction
https://github.com/eeric/LSNet_supplement

**Comment by dongdongyee** [comment]
You can use a higher version of PyTorch, e.g. 1.8.0, in case you have a GPU that only works under CUDA 11+
What you need to do is to change some code in code/mmdet/models/dense_heads/lsnet_head.py
The error is caused by inplace operations. You can change all the _variable1 *= variable2_ into _variable1 = variable1 * variable2_
I've tested it and it should work.

**Comment by wz66-desige** [comment]
运行 ./tools/dist_test.sh configs/sem_fpn/fpn_lsnet_t_ade20k_40k.py pretrain/lsnet_t_semfpn.pth 1 --eval mIoU

报错
/home/wz/anaconda3/envs/lsnet/lib/python3.9/site-packages/torch/distributed/launch.py:208: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use-env is set by default in torchrun.
If your script expects `--local-rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  main()
/home/wz/anaconda3/envs/lsnet/lib/python3.9/site-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
/home/wz/anaconda3/envs/lsnet/lib/python3.9/site-packages/mmcv/cnn/bricks/transformer.py:33: UserWarning: Fail to import ``MultiScaleDeformableAttention`` from ``mmcv.ops.multi_scale_deform_attn``, You should install ``mmcv-full`` if you need this module. 
  warnings.warn('Fail to import ``MultiScaleDeformableAttention`` from '
Traceback (most recent call last):
  File "/home/wz/lsnet/lsnet-master/segmentation/./tools/test.py", line 16, in <module>
    from mmseg.apis import multi_gpu_test, single_gpu_test
  File "/home/wz/anaconda3/envs/lsnet/lib/python3.9/site-packages/mmseg/apis/__init__.py", line 2, in <module>
    from .inference import inference_segmentor, init_segmentor, show_result_pyplot
  File "/home/wz/anaconda3/envs/lsnet/lib/python3.9/site-packages/mmseg/apis/inference.py", line 9, in <module>
    from mmseg.models import build_segmentor
  File "/home/wz/anaconda3/envs/lsnet/lib/python3.9/site-packages/mmseg/models/__init__.py", line 2, in <module>
    from .backbones import *  # noqa: F401,F403
  File "/home/wz/anaconda3/envs/lsnet/lib/python3.9/site-packages/mmseg/models/backbones/__init__.py", line 7, in <module>
    from .fast_scnn import FastSCNN
  File "/home/wz/anaconda3/envs/lsnet/lib/python3.9/site-packages/mmseg/models/backbones/fast_scnn.py", line 7, in <module>
    from mmseg.models.decode_heads.psp_head import PPM
  File "/home/wz/anaconda3/envs/lsnet/lib/python3.9/site-packages/mmseg/models/decode_heads/__init__.py", line 2, in <module>
    from .ann_head import ANNHead
  File "/home/wz/anaconda3/envs/lsnet/lib/python3.9/site-packages/mmseg/models/decode_heads/ann_head.py", line 8, in <module>
    from .decode_head import BaseDecodeHead
  File "/home/wz/anaconda3/envs/lsnet/lib/python3.9/site-packages/mmseg/models/decode_heads/decode_head.py", line 12, in <module>
    from ..losses import accuracy
  File "/home/wz/anaconda3/envs/lsnet/lib/python3.9/site-packages/mmseg/models/losses/__init__.py", line 6, in <module>
    from .focal_loss import FocalLoss
  File "/home/wz/anaconda3/envs/lsnet/lib/python3.9/site-packages/mmseg/models/losses/focal_loss.py", line 6, in <module>
    from mmcv.ops import sigmoid_focal_loss as _sigmoid_focal_loss
  File "/home/wz/anaconda3/envs/lsnet/lib/python3.9/site-packages/mmcv/ops/__init__.py", line 3, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "/home/wz/anaconda3/envs/lsnet/lib/python3.9/site-packages/mmcv/ops/active_rotated_filter.py", line 10, in <module>
    ext_module = ext_loader.load_ext(
  File "/home/wz/anaconda3/envs/lsnet/lib/python3.9/site-packages/mmcv/utils/ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/home/wz/anaconda3/envs/lsnet/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /home/wz/anaconda3/envs/lsnet/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by /home/wz/anaconda3/envs/lsnet/lib/python3.9/site-packages/mmcv/_ext.cpython-39-x86_64-linux-gnu.so)
E0806 11:44:49.910143 136054090192704 torch/distributed/elastic/multiprocessing/api.py:833] failed (exitcode: 1) local_rank: 0 (pid: 533798) of binary: /home/wz/anaconda3/envs/lsnet/bin/python
Traceback (most recent call last):
  File "/home/wz/anaconda3/envs/lsnet/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/wz/anaconda3/envs/lsnet/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/wz/anaconda3/envs/lsnet/lib/python3.9/site-packages/torch/distributed/launch.py", line 208, in <module>
    main()
  File "/home/wz/anaconda3/envs/lsnet/lib/python3.9/site-packages/typing_extensions.py", line 2853, in wrapper
    return arg(*args, **kwargs)
  File "/home/wz/anaconda3/envs/lsnet/lib/python3.9/site-packages/torch/distributed/launch.py", line 204, in main
    launch(args)
  File "/home/wz/anaconda3/envs/lsnet/lib/python3.9/site-packages/torch/distributed/launch.py", line 189, in launch
    run(args)
  File "/home/wz/anaconda3/envs/lsnet/lib/python3.9/site-packages/torch/distributed/run.py", line 892, in run
    elastic_launch(
  File "/home/wz/anaconda3/envs/lsnet/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 133, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/wz/anaconda3/envs/lsnet/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
./tools/test.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-08-06_11:44:49
  host      : wz-B760M-H-M-2
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 533798)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

请问这是什么问题
