### ISSUE TITLE
RuntimeError: stack expects each tensor to be equal size, but got [2, 51] at entry 0 and [5, 51] at entry 1

### ISSUE THREAD

**Issue by crazysboy** [Duankaiwen/LSNet#24]
作者你好，你在部署运行训练你的模型时有没有遇到RuntimeError: stack expects each tensor to be equal size, but got [2, 51] at entry 0 and [5, 51] at entry 1 这个错误，请问我该怎么解决

**Comment by Duankaiwen** [comment]
请把完整日志发一下

**Comment by crazysboy** [comment]
2021-09-09 16:48:34,613 - mmdet - INFO - workflow: [('train', 1)], max: 12 epochs
Traceback (most recent call last):
  File "/media/zhaozhenxi/新加卷/mmdetection_zuixin/tools/train.py", line 190, in <module>
    main()
  File "/media/zhaozhenxi/新加卷/mmdetection_zuixin/tools/train.py", line 186, in main
    meta=meta)
  File "/media/zhaozhenxi/新加卷/mmdetection_zuixin/mmdet/apis/train.py", line 174, in train_detector
    runner.run(data_loaders, cfg.workflow)###################
  File "/media/zhaozhenxi/新加卷/mmdetection_zuixin/mmcv-master/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/media/zhaozhenxi/新加卷/mmdetection_zuixin/mmcv-master/mmcv/runner/epoch_based_runner.py", line 47, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/root/anaconda3/envs/openmmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/root/anaconda3/envs/openmmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/root/anaconda3/envs/openmmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/root/anaconda3/envs/openmmlab/lib/python3.7/site-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/root/anaconda3/envs/openmmlab/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/root/anaconda3/envs/openmmlab/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/media/zhaozhenxi/新加卷/mmdetection_zuixin/mmcv-master/mmcv/parallel/collate.py", line 81, in collate
    for key in batch[0]
  File "/media/zhaozhenxi/新加卷/mmdetection_zuixin/mmcv-master/mmcv/parallel/collate.py", line 81, in <dictcomp>
    for key in batch[0]
  File "/media/zhaozhenxi/新加卷/mmdetection_zuixin/mmcv-master/mmcv/parallel/collate.py", line 84, in collate
    return default_collate(batch)#batch wei(1, 51)
  File "/root/anaconda3/envs/openmmlab/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 64, in default_collate
    return default_collate([torch.as_tensor(b) for b in batch])
  File "/root/anaconda3/envs/openmmlab/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 56, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: stack expects each tensor to be equal size, but got [1, 51] at entry 0 and [2, 51] at entry 1


Process finished with exit code 1

作者你好，完整的日志发给你了，请你帮我看看。我把你的部署到最新的mmdect中，模型加载没有问题但好像是数据加载训练出现了这个错误

**Comment by Duankaiwen** [comment]
我用的mmcv 0.6.2版本，把mmcv改成0.6.2应该就可以了
