### ISSUE TITLE
Error with segmentation

### ISSUE THREAD

**Issue by ming71** [Duankaiwen/LSNet#4]
Thanks for your good job! 
When I  tested the code on the segmentation task, there are the following bug report:

```
2021-05-14 21:13:25,373 - mmdet - INFO - workflow: [('train', 1)], max: 12 epochs
Traceback (most recent call last):
  File "tools/train.py", line 159, in <module>
    main()
  File "tools/train.py", line 155, in main
    meta=meta)
  File "/home/bit/ming7/LSNet/mmdet/apis/train.py", line 128, in train_detector
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/bit/ming7/LSNet/mmcv/mmcv/runner/epoch_based_runner.py", line 122, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/bit/ming7/LSNet/mmcv/mmcv/runner/epoch_based_runner.py", line 27, in train
    for i, data_batch in enumerate(data_loader):
  File "/home/bit/anaconda2/envs/lsnet/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/bit/anaconda2/envs/lsnet/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 838, in _next_data
    return self._process_data(data)
  File "/home/bit/anaconda2/envs/lsnet/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/home/bit/anaconda2/envs/lsnet/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
TypeError: __init__() missing 4 required positional arguments: 'casting', 'from_', 'to', and 'i'
```
It seems that there is something wrong with my annotation? (refer to this [url](https://discuss.pytorch.org/t/bug-in-pytorch-with-yolact/110573/10)). But I have no idea how to solve it.
Hope to get your reply, thanks !

**Comment by ming71** [comment]
I've converted the annotations to the `lsvr` type according to your comment, and my config is `lsnet_segm_r50_fpn_1x_isaid` . BTW, there is no problem training on detection task with `lsnet_bbox_r50_fpn_1x_isaid`.

**Comment by ming71** [comment]
Fixed, this is a bug from the related code about cenernet.

**Comment by eeric** [comment]
Installation instruction
https://github.com/eeric/LSNet_supplement

**Comment by eeric** [comment]
Installation instruction
https://github.com/eeric/LSNet_supplement
